### PR TITLE
Default value of nodejs v10 http response status code  is 404

### PR DESCRIPTION
**Pull request by hsuehic**
Default value of nodejs v10 http response status code  is 404

### CODE REVIEW

**Comment by lujjjh** [comment]
Thanks for the contribution.

I did not reproduce a 404 with Node v10.18.0. Would you please provide a minimal, reproducible example?

Thank you.

**Comment by hsuehic** [comment]
Here is the repo for example. https://github.com/hsuehic/restc-404-example
When browse using browser like chrome directly, no errors would occur. But if the application running behind a reverse proxy server like nginx the 404 issue will lead to blank page, since if reponse status code is 404, nginx would not process the body.

**Comment by lujjjh** [comment]
> Here is the repo for example. https://github.com/hsuehic/restc-404-example
> When browse using browser like chrome directly, no errors would occur. But if the application running behind a reverse proxy server like nginx the 404 issue will lead to blank page, since if reponse status code is 404, nginx would not process the body.

Got it. Related with https://github.com/koajs/koa/issues/705.

Thank you for the nice fix.

Please run `npm run lint-fix` and squash these commits into one.

And I'll merge it.

**Comment by hsuehic** [comment]
thanks. done

**Pull request merged**
